### PR TITLE
Implemented Belfiore codes DB and name/surname check

### PR DESCRIPTION
**Pull request by eutampieri**
Let me know if you have any issues!
I plan to implement the name validation in the next month or so.

### CODE REVIEW

**Comment by lordarthas** [comment]
Hi there!

I'm a bit out of the Rust world at present time, so unable to maintain this promptly.

Would you be willing to take the crate maintenance work over? I would be happy to hand it over to you.

**Comment by eutampieri** [comment]
That's fine, but I'm not a great rust dev either!

**Comment by lordarthas** [comment]
Okk, you should now be able to manage the repository and push/pull etc.

**Comment by eutampieri** [comment]
Yes, now I am able but you should transfer the crate on crates.io too

**Comment by eutampieri** [comment]
https://crates.io/crates/codice_fiscale/owners from this page

**Comment by lordarthas** [comment]
Sure! Is your username on crates.io eutampieri as well?

**Comment by eutampieri** [comment]
Yes!

**Comment by eutampieri** [comment]
Excuse me, could you check your fiscal code? I think there's a bug somewhere. I sent you an email with my results

**Pull request merged**
